/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: gocv/gocv.swigcxx

package gocv

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

var _wrap_Swig_free_gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_gocv_7cd4b6474b96a291, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_gocv_7cd4b6474b96a291 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_gocv_7cd4b6474b96a291, _swig_p)
	return
}
var _wrap_std_set_gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_std_set(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_std_set_gocv_7cd4b6474b96a291, _swig_p)
	return
}

func SetStd(arg1 Namespace) {
	_swig_wrap_std_set(arg1.Swigcptr())
}

var _wrap_std_get_gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_std_get() (base SwigcptrNamespace) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_std_get_gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GetStd() (_swig_ret Namespace) {
	return _swig_wrap_std_get()
}

var _wrap_Mat64ToGcvMat__gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_Mat64ToGcvMat_(base int, _ int, _ uintptr) (_ SwigcptrCv_Mat) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Mat64ToGcvMat__gocv_7cd4b6474b96a291, _swig_p)
	return
}

func Mat64ToGcvMat_(arg1 int, arg2 int, arg3 Std_vector_Sl_double_Sg_) (_swig_ret Cv_Mat) {
	return _swig_wrap_Mat64ToGcvMat_(arg1, arg2, arg3.Swigcptr())
}

var _wrap_cv_set_gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_cv_set(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_cv_set_gocv_7cd4b6474b96a291, _swig_p)
	return
}

func SetCv(arg1 Namespace) {
	_swig_wrap_cv_set(arg1.Swigcptr())
}

var _wrap_cv_get_gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_cv_get() (base SwigcptrNamespace) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_cv_get_gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GetCv() (_swig_ret Namespace) {
	return _swig_wrap_cv_get()
}

var _wrap_GcvInitCameraMatrix2D__gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_GcvInitCameraMatrix2D_(base uintptr, _ uintptr, _ uintptr, _ float64) (_ SwigcptrCv_Mat) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_GcvInitCameraMatrix2D__gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GcvInitCameraMatrix2D_(arg1 Std_vector_Sl_cv_Point3f_Sg_, arg2 Std_vector_Sl_cv_Point2f_Sg_, arg3 Cv_Size, arg4 float64) (_swig_ret Cv_Mat) {
	return _swig_wrap_GcvInitCameraMatrix2D_(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4)
}

var _wrap_GcvCalibrateCamera__gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_GcvCalibrateCamera_(base uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ uintptr, _ int) (_ float64) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_GcvCalibrateCamera__gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GcvCalibrateCamera_(arg1 Std_vector_Sl_cv_Point3f_Sg_, arg2 Std_vector_Sl_cv_Point2f_Sg_, arg3 Cv_Size, arg4 Cv_Mat, arg5 Cv_Mat, arg6 Cv_Mat, arg7 Cv_Mat, arg8 int) (_swig_ret float64) {
	return _swig_wrap_GcvCalibrateCamera_(arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4.Swigcptr(), arg5.Swigcptr(), arg6.Swigcptr(), arg7.Swigcptr(), arg8)
}

var _wrap_GcvRodrigues__gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_GcvRodrigues_(base uintptr, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_GcvRodrigues__gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GcvRodrigues_(arg1 Cv_Mat, arg2 Cv_Mat) {
	_swig_wrap_GcvRodrigues_(arg1.Swigcptr(), arg2.Swigcptr())
}

var _wrap_GcvGaussianBlur__gocv_7cd4b6474b96a291 unsafe.Pointer

func _swig_wrap_GcvGaussianBlur_(base int, _ uintptr, _ uintptr, _ uintptr, _ float64, _ float64, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_GcvGaussianBlur__gocv_7cd4b6474b96a291, _swig_p)
	return
}

func GcvGaussianBlur_(arg1 Cv_Mat, arg2 Cv_Mat, arg3 Cv_Size, arg4 float64, _swig_args ...interface{}) {
	var arg5 float64
	if len(_swig_args) > 0 {
		arg5 = _swig_args[0].(float64)
	}
	var arg6 int
	if len(_swig_args) > 1 {
		arg6 = _swig_args[1].(int)
	}
	_swig_wrap_GcvGaussianBlur_(len(_swig_args), arg1.Swigcptr(), arg2.Swigcptr(), arg3.Swigcptr(), arg4, arg5, arg6)
}


type SwigcptrStd_vector_Sl_cv_Point3f_Sg_ uintptr
type Std_vector_Sl_cv_Point3f_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_cv_Point3f_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_double_Sg_ uintptr
type Std_vector_Sl_double_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_double_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrCv_Mat uintptr
type Cv_Mat interface {
	Swigcptr() uintptr;
}
func (p SwigcptrCv_Mat) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrCv_Size uintptr
type Cv_Size interface {
	Swigcptr() uintptr;
}
func (p SwigcptrCv_Size) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrNamespace uintptr
type Namespace interface {
	Swigcptr() uintptr;
}
func (p SwigcptrNamespace) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_cv_Point2f_Sg_ uintptr
type Std_vector_Sl_cv_Point2f_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_cv_Point2f_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

