/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: gocv/gocv.swigcxx */

#define SWIGMODULE gocv
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




static void *_swig_goallocate(size_t len) {
  struct {
    size_t len;
    void *ret;
  } SWIGSTRUCTPACKED a;
  a.len = len;
  crosscall2(_cgo_allocate, &a, (int) sizeof a);
  return a.ret;
}




/* This is here for backward compatibility, but it will not work
   with Go 1.5 or later.  Do not use it in new code.  */
static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "opencv2/core/core.hpp"
#include "gocv_core.hpp"


#include <vector>
#include <stdexcept>


#include "gocv_calib3d.hpp"


#include "gocv_imgproc.hpp"

#ifdef __cplusplus
extern "C" {
#endif

void
_wrap_Swig_free_gocv_7cd4b6474b96a291(void *swig_v)
{
  void *arg1 = (void *) 0 ;
  void *_swig_go_0;
  struct swigargs {
    void *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void
_wrap_Swig_malloc_gocv_7cd4b6474b96a291(void *swig_v)
{
  int arg1 ;
  void *result = 0 ;
  intgo _swig_go_0;
  void *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    void *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_std_set_gocv_7cd4b6474b96a291(void *swig_v)
{
  namespace arg1 ;
  namespace *argp1 ;
  namespace *_swig_go_0;
  struct swigargs {
    namespace *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  
  argp1 = (namespace *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null namespace");
  }
  arg1 = (namespace)*argp1;
  
  
  std = arg1;
  
}


void
_wrap_std_get_gocv_7cd4b6474b96a291(void *swig_v)
{
  namespace result;
  namespace *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    namespace *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = std;
  {
    namespace * resultptr = (namespace *)malloc(sizeof(namespace));
    memmove(resultptr, &result, sizeof(namespace));
    *(namespace **)&_swig_go_result = resultptr;
  }
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_Mat64ToGcvMat__gocv_7cd4b6474b96a291(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  std::vector< double > arg3 ;
  std::vector< double > *argp3 ;
  cv::Mat result;
  intgo _swig_go_0;
  intgo _swig_go_1;
  std::vector< double > *_swig_go_2;
  cv::Mat *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    intgo arg2;
    std::vector< double > *arg3;
    long : 0;
    cv::Mat *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  argp3 = (std::vector< double > *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null std::vector< double >");
  }
  arg3 = (std::vector< double >)*argp3;
  
  
  swig_stktop = _swig_topofstack();
  result = Mat64ToGcvMat_(arg1,arg2,arg3);
  {
    cv::Mat * resultptr = (cv::Mat *)malloc(sizeof(cv::Mat));
    memmove(resultptr, &result, sizeof(cv::Mat));
    *(cv::Mat **)&_swig_go_result = resultptr;
  }
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_cv_set_gocv_7cd4b6474b96a291(void *swig_v)
{
  namespace arg1 ;
  namespace *argp1 ;
  namespace *_swig_go_0;
  struct swigargs {
    namespace *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  
  argp1 = (namespace *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null namespace");
  }
  arg1 = (namespace)*argp1;
  
  
  cv = arg1;
  
}


void
_wrap_cv_get_gocv_7cd4b6474b96a291(void *swig_v)
{
  namespace result;
  namespace *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    namespace *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = cv;
  {
    namespace * resultptr = (namespace *)malloc(sizeof(namespace));
    memmove(resultptr, &result, sizeof(namespace));
    *(namespace **)&_swig_go_result = resultptr;
  }
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_GcvInitCameraMatrix2D__gocv_7cd4b6474b96a291(void *swig_v)
{
  VecPoint3f arg1 ;
  VecPoint2f arg2 ;
  cv::Size arg3 ;
  double arg4 ;
  VecPoint3f *argp1 ;
  VecPoint2f *argp2 ;
  cv::Size *argp3 ;
  cv::Mat result;
  std::vector< cv::Point3f > *_swig_go_0;
  std::vector< cv::Point2f > *_swig_go_1;
  cv::Size *_swig_go_2;
  double _swig_go_3;
  cv::Mat *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    std::vector< cv::Point3f > *arg1;
    std::vector< cv::Point2f > *arg2;
    cv::Size *arg3;
    double arg4;
    long : 0;
    cv::Mat *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  _swig_go_3 = swig_a->arg4;
  
  argp1 = (VecPoint3f *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null VecPoint3f");
  }
  arg1 = (VecPoint3f)*argp1;
  
  
  argp2 = (VecPoint2f *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null VecPoint2f");
  }
  arg2 = (VecPoint2f)*argp2;
  
  
  argp3 = (cv::Size *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Size");
  }
  arg3 = (cv::Size)*argp3;
  
  arg4 = (double)_swig_go_3; 
  
  swig_stktop = _swig_topofstack();
  result = GcvInitCameraMatrix2D_(arg1,arg2,arg3,arg4);
  {
    cv::Mat * resultptr = (cv::Mat *)malloc(sizeof(cv::Mat));
    memmove(resultptr, &result, sizeof(cv::Mat));
    *(cv::Mat **)&_swig_go_result = resultptr;
  }
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_GcvCalibrateCamera__gocv_7cd4b6474b96a291(void *swig_v)
{
  VecPoint3f arg1 ;
  VecPoint2f arg2 ;
  cv::Size arg3 ;
  cv::Mat *arg4 = 0 ;
  cv::Mat arg5 ;
  cv::Mat *arg6 = 0 ;
  cv::Mat *arg7 = 0 ;
  int arg8 ;
  VecPoint3f *argp1 ;
  VecPoint2f *argp2 ;
  cv::Size *argp3 ;
  cv::Mat *argp5 ;
  double result;
  std::vector< cv::Point3f > *_swig_go_0;
  std::vector< cv::Point2f > *_swig_go_1;
  cv::Size *_swig_go_2;
  cv::Mat *_swig_go_3;
  cv::Mat *_swig_go_4;
  cv::Mat *_swig_go_5;
  cv::Mat *_swig_go_6;
  intgo _swig_go_7;
  double _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    std::vector< cv::Point3f > *arg1;
    std::vector< cv::Point2f > *arg2;
    cv::Size *arg3;
    cv::Mat *arg4;
    cv::Mat *arg5;
    cv::Mat *arg6;
    cv::Mat *arg7;
    intgo arg8;
    long : 0;
    double result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  _swig_go_3 = swig_a->arg4;
  _swig_go_4 = swig_a->arg5;
  _swig_go_5 = swig_a->arg6;
  _swig_go_6 = swig_a->arg7;
  _swig_go_7 = swig_a->arg8;
  
  argp1 = (VecPoint3f *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null VecPoint3f");
  }
  arg1 = (VecPoint3f)*argp1;
  
  
  argp2 = (VecPoint2f *)_swig_go_1;
  if (argp2 == NULL) {
    _swig_gopanic("Attempt to dereference null VecPoint2f");
  }
  arg2 = (VecPoint2f)*argp2;
  
  
  argp3 = (cv::Size *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Size");
  }
  arg3 = (cv::Size)*argp3;
  
  arg4 = *(cv::Mat **)&_swig_go_3; 
  
  argp5 = (cv::Mat *)_swig_go_4;
  if (argp5 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Mat");
  }
  arg5 = (cv::Mat)*argp5;
  
  arg6 = *(cv::Mat **)&_swig_go_5; 
  arg7 = *(cv::Mat **)&_swig_go_6; 
  arg8 = (int)_swig_go_7; 
  
  swig_stktop = _swig_topofstack();
  result = (double)GcvCalibrateCamera_(arg1,arg2,arg3,*arg4,arg5,*arg6,*arg7,arg8);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_GcvRodrigues__gocv_7cd4b6474b96a291(void *swig_v)
{
  cv::Mat arg1 ;
  cv::Mat *arg2 = 0 ;
  cv::Mat *argp1 ;
  cv::Mat *_swig_go_0;
  cv::Mat *_swig_go_1;
  struct swigargs {
    cv::Mat *arg1;
    cv::Mat *arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  
  argp1 = (cv::Mat *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Mat");
  }
  arg1 = (cv::Mat)*argp1;
  
  arg2 = *(cv::Mat **)&_swig_go_1; 
  
  GcvRodrigues_(arg1,*arg2);
  
}


void
_wrap_GcvGaussianBlur__gocv_7cd4b6474b96a291(void *swig_v)
{
  cv::Mat arg1 ;
  cv::Mat *arg2 = 0 ;
  cv::Size arg3 ;
  double arg4 ;
  double arg5 = (double) 0 ;
  int arg6 = (int) BORDER_DEFAULT ;
  cv::Mat *argp1 ;
  cv::Size *argp3 ;
  cv::Mat *_swig_go_0;
  cv::Mat *_swig_go_1;
  cv::Size *_swig_go_2;
  double _swig_go_3;
  double _swig_go_4;
  intgo _swig_go_5;
  struct swigargs {
    intgo _swig_optargc;
    cv::Mat *arg1;
    cv::Mat *arg2;
    cv::Size *arg3;
    double arg4;
    double arg5;
    intgo arg6;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  _swig_go_3 = swig_a->arg4;
  _swig_go_4 = swig_a->arg5;
  _swig_go_5 = swig_a->arg6;
  
  argp1 = (cv::Mat *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Mat");
  }
  arg1 = (cv::Mat)*argp1;
  
  arg2 = *(cv::Mat **)&_swig_go_1; 
  
  argp3 = (cv::Size *)_swig_go_2;
  if (argp3 == NULL) {
    _swig_gopanic("Attempt to dereference null cv::Size");
  }
  arg3 = (cv::Size)*argp3;
  
  arg4 = (double)_swig_go_3; 
  if (swig_a->_swig_optargc > 0) {
    arg5 = (double)_swig_go_4; 
  }
  if (swig_a->_swig_optargc > 1) {
    arg6 = (int)_swig_go_5; 
  }
  
  GcvGaussianBlur_(arg1,*arg2,arg3,arg4,arg5,arg6);
  
}


#ifdef __cplusplus
}
#endif

